<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api\V1;

use App\Enum\ActivityAction;
use App\Enum\ActivityModule;
use App\Enum\UserType;
use App\Http\Controllers\Api\ApiController;
use App\Http\Requests\V1\Auth\ResendVerificationRequest;
use App\Models\User;
use App\Support\ActivityLogger;
use Illuminate\Auth\Events\Verified;
use Illuminate\Http\JsonResponse;

class VerificationController extends ApiController
{
    /**
     * Verify an email address via signed link.
     *
     * Mirrors Livewire\Auth\VerifyEmail::mount(), except keyed by `external_id`
     * rather than the raw numeric PK — a public-facing link should never
     * expose a sequential, enumerable id. The {id}/{hash} signature (checked
     * by the `signed` route middleware, generated by
     * UrlResolver::verificationUrl()) is the only proof of identity here —
     * this runs before any Sanctum token exists, never behind auth:sanctum.
     */
    public function verify(string $id, string $hash): JsonResponse
    {
        $user = User::where('external_id', $id)->firstOrFail();

        abort_unless(hash_equals(sha1($user->getEmailForVerification()), $hash), 403);

        if ($user->hasVerifiedEmail()) {
            return $this->success(null, 'Email already verified.');
        }

        $user->markEmailAsVerified();

        // AuthActivityListener::handleVerified() logs this for free.
        event(new Verified($user));

        return $this->success(null, 'Email verified successfully.');
    }

    /**
     * Resend the email verification link.
     *
     * Always responds the same way regardless of whether the account exists
     * or is already verified — never leaks account existence to a guest caller.
     */
    public function resend(ResendVerificationRequest $request): JsonResponse
    {
        $user = User::where('email', $request->validated('email'))
            ->where('type', UserType::App)
            ->first();

        if ($user && ! $user->hasVerifiedEmail()) {
            $user->sendEmailVerificationNotification();

            // Mirrors Users/Show::resendVerificationEmail()'s admin-triggered
            // shape, causer the user themselves — self-initiated, no session.
            ActivityLogger::log(ActivityModule::User, ActivityAction::Sent, $user, [
                'type' => 'email_verification',
            ], causer: $user);
        }

        return $this->success(null, 'If that email exists and is unverified, a verification link has been sent.');
    }
}
